site_name: Sink
site_author: shihr
nav:
    - Home: index.md
    - System:
        - epel源: system/epel源.md
        - rpms产出: system/rpms产出.md
        - rsync配置: system/rsync配置.md
        - 主机不能连接mariadb: system/主机不能连接mariadb.md
        - 修改centos7语言: system/修改centos7语言.md
        - 修改mariadb编码类型: system/修改mariadb编码类型.md
        - 关闭selinux: system/关闭selinux.md
        - 开启图形界面: system/开启图形界面.md
        - 文本安装时磁盘可选: system/文本安装时磁盘可选.md
        - 改变系统时区: system/改变系统时区.md
        - 磁盘容量扩充: system/磁盘容量扩充.md
        - 网卡不存在: system/网卡不存在.md
        - 通过shell命令写文件: system/通过shell命令写文件.md
    - 虚拟机转换:
        - libguestfs架构: 虚拟机转换/libguestfs架构.md
        - 以ova为例virt-v2v磁盘转换流程: 虚拟机转换/以ova为例virt-v2v磁盘转换流程.md
        - virt-p2v-make-disk脚本分析: 虚拟机转换/virt-p2v-make-disk脚本分析.md
        - virt-p2v介绍: 虚拟机转换/virt-p2v介绍.md
        - virt-p2v磁盘转换流程: 虚拟机转换/virt-p2v磁盘转换流程.md
        - VMware-ova转换: 虚拟机转换/VMware-ova转换.md
        - VMware-vmx转换: 虚拟机转换/VMware-vmx转换.md
        - VMware-vCenter转换: 虚拟机转换/VMware-vCenter转换.md
        - VMware-ESXI-hypervisor转换: 虚拟机转换/VMware-ESXI-hypervisor转换.md
        - VMware-vddk转换: 虚拟机转换/VMware-vddk转换.md
        - Xen转换: 虚拟机转换/Xen转换.md
    - 虚拟机转换脚本使用说明:
        - 文档阅读说明: 虚拟机转换脚本使用说明/文档阅读说明.md
        - 转换服务器的搭建: 虚拟机转换脚本使用说明/转换服务器的搭建.md
        - 1.ova转换模式: 虚拟机转换脚本使用说明/1.ova转换模式.md
        - 2.vmx转换模式: 虚拟机转换脚本使用说明/2.vmx转换模式.md
        - 3.ESXi转换模式: 虚拟机转换脚本使用说明/3.ESXi转换模式.md
        - 4.vCenter转换模式: 虚拟机转换脚本使用说明/4.vCenter转换模式.md
        - 5.vddk转换模式: 虚拟机转换脚本使用说明/5.vddk转换模式.md
        - 6.xen转换模式: 虚拟机转换脚本使用说明/6.xen转换模式.md
        - 转换到ovirt平台: 虚拟机转换脚本使用说明/转换到ovirt平台.md
    - Spice:
        - 简介: spice/简介.md
        - 使用范例: spice/使用范例.md
        - 函数所在文件: spice/函数所在文件.md
    - Python:
        - event线程: python/event线程.md
        - json格式处理: python/json格式处理.md
        - 执行shell命令: python/执行shell命令.md
        - 超时装饰器: python/超时装饰器.md
    - Other:
        - CSDN语法: other/CSDN语法.md
        - h5ai美化目录: other/h5ai美化目录.md
        - vdsm启动失败: other/vdsm启动失败.md
        - 制作iso镜像: other/制作iso镜像.md
        - 没有打印日志: other/没有打印日志.md
        - 编译安装vdsm之后主机安装失败: other/编译安装vdsm之后主机安装失败.md
    - Make:
        - 10.使用隐含规则: make/10.使用隐含规则.md
        - 11.使用make更新归档文件: make/11.使用make更新归档文件.md
        - 16.Makefile约定: make/16.Makefile约定.md
        - 4.编写规则: make/4.编写规则.md
        - 5.编写recipes: make/5.编写recipes.md
        - 6.变量: make/6.变量.md
        - 7.Makefile中的条件语句: make/7.Makefile中的条件语句.md
        - 8.转换文本函数: make/8.转换文本函数.md
        - 简介: make/简介.md
    - M4:
        - 11.文本处理的宏: m4/11.文本处理的宏.md
        - 6.条件、循环、递归: m4/6.条件、循环、递归.md
        - 简介: m4/简介.md
    - Java:
        - IO: java/IO.md
        - 作用范围级别: java/作用范围级别.md
        - synchronized关键字: java/synchronized关键字.md
    - servlet:
        - 1.简介: servlet/1.简介.md
        - 2.生命周期: servlet/2.生命周期.md
        - 3.示例: servlet/3.示例.md
        - 4.过滤器: servlet/4.过滤器.md
        - 5.异常处理: servlet/5.异常处理.md
        - 6.Cookie: servlet/6.Cookie.md
        - 7.Session 跟踪: servlet/7.Session 跟踪.md
        - 8.文件上传: servlet/8.文件上传.md
        - 10.作用域: servlet/10.作用域.md
    - Spring:
        - 文件上传: spring/文件上传.md
    - Spring Boot:
        - 1.说明: springboot/1.说明.md
        - 2.Maven: springboot/2.Maven.md
        - 24.Application 属性文件: springboot/24.Application 属性文件.md
        - 25.Profiles: springboot/25.Profiles.md
        - 26.日志: springboot/26.日志.md
        - 29.开发web应用: springboot/29.开发web应用.md
    - 设计模式:
        - 设计原则: 设计模式/设计原则.md
        - 模式: 设计模式/模式.md
    - MyBatis:
        - 简介.md: mybatis/简介.md
        - XML配置.md: mybatis/XML配置.md
        - 注意事项.md: mybatis/注意事项.md
    - HTTP协议:
        - 简介.md: http协议/简介.md
        - HTTP 报文内的 HTTP 信息.md: http协议/HTTP 报文内的 HTTP 信息.md
        - 返回结果的 HTTP 状态码.md: http协议/返回结果的 HTTP 状态码.md
        - 与 HTTP 协作的 Web 服务器.md: http协议/与 HTTP 协作的 Web 服务器.md
        - HTTP 首部.md: http协议/HTTP 首部.md
        - HTTPS.md: http协议/HTTPS.md
    - Linux网络编程:
        - 函数: linux网络编程/函数.md
        - socket通信流程: linux网络编程/socket通信流程.md
        - 简单tcp通信实现: linux网络编程/简单tcp通信实现.md
    - Gluster:
        - gluster安装: gluster/gluster安装.md
        - ovirt的gluster数据恢复bug: gluster/ovirt的gluster数据恢复bug.md
        - 清理不可用的brick: gluster/清理不可用的brick.md
        - 结点故障: gluster/结点故障.md
    - Git:
        - git rebase(修改历史提交): git/git rebase(修改历史提交).md
        - windows无法使用git克隆: git/windows无法使用git克隆.md
    - Gerrit:
        - Apache代理添加新用户: gerrit/Apache代理添加新用户.md
        - Gerrit submit change after abandoning its parent: gerrit/Gerrit submit change after abandoning its parent.md
        - 使用Apache代理路径错误: gerrit/使用Apache代理路径错误.md
        - 刷新gerrit项目列表: gerrit/刷新gerrit项目列表.md
    - Datastruct:
        - 二叉树: datastruct/二叉树.md
        - 散列表: datastruct/散列表.md
        - 红黑树: datastruct/红黑树.md
    - Command:
        - linux挂载windows共享文件夹: command/linux挂载windows共享文件夹.md
        - sed: command/sed.md
        - ssh免密登录: command/ssh免密登录.md
        - shell脚本自动输入: command/shell脚本自动输入.md
        - tar命令打包去掉路径前缀: command/tar命令打包去掉路径前缀.md
        - wget用法: command/wget用法.md
        - 显示文件夹大小: command/显示文件夹大小.md
        - 更新、禁用yum仓库、只下载rpm: command/更新、禁用yum仓库、只下载rpm.md
        - 添加公钥: command/添加公钥.md
    - C and c++:
        - 动态编译: c and c++/动态编译.md
        - 程序运行时间: c and c++/程序运行时间.md
    - Bash:
        - 3.基本shell功能: bash/3.基本shell功能.md
        - 4.shell内置命令: bash/4.shell内置命令.md
    - Automake:
        - 10.其它GNU工具: automake/10.其它GNU工具.md
        - 12.安装: automake/12.安装.md
        - 13.清理: automake/13.清理.md
        - 14.发布: automake/14.发布.md
        - 15.测试套件的支持: automake/15.测试套件的支持.md
        - 18.规则杂项: automake/18.规则杂项.md
        - 19.Include: automake/19.Include.md
        - 20.条件语句: automake/20.条件语句.md
        - 23.Automake不能满足使用时: automake/23.Automake不能满足使用时.md
        - 5.创建Makefile.in: automake/5.创建Makefile.in.md
        - 6.扫描configure.ac，使用aclocal: automake/6.扫描configure.ac，使用aclocal.md
        - 7.文件夹: automake/7.文件夹.md
        - 8.构建程序和库: automake/8.构建程序和库.md
        - 9.其它派生对象: automake/9.其它派生对象.md
        - 简介: automake/简介.md
    - Autogen:
        - 简介: autogen/简介.md
    - Autoconf:
        - 10.编写Autoconf宏: autoconf/10.编写Autoconf宏.md
        - 11.便携式shell编程: autoconf/11.便携式shell编程.md
        - 14.手动配置: autoconf/14.手动配置.md
        - 15.Site配置: autoconf/15.Site配置.md
        - 4.初始化和输出文件: autoconf/4.初始化和输出文件.md
        - 5.现有测试: autoconf/5.现有测试.md
        - 6.编写测试: autoconf/6.编写测试.md
        - 7.测试结果: autoconf/7.测试结果.md
        - 8.使用M4编程: autoconf/8.使用M4编程.md
        - 9.使用M4sh编程: autoconf/9.使用M4sh编程.md
        - 简介: autoconf/简介.md
    - Algorithm:
        - 复杂度分析: algorithm/复杂度分析.md
        - 选择排序: algorithm/选择排序.md
theme: readthedocs
# theme: windmill