site_name: Sink
site_author: shihr
nav:
    - Home: index.md
    - System:
        - epel源: system/epel源.md
        - rpms产出: system/rpms产出.md
        - rsync配置: system/rsync配置.md
        - 主机不能连接mariadb: system/主机不能连接mariadb.md
        - 修改centos7语言: system/修改centos7语言.md
        - 修改mariadb编码类型: system/修改mariadb编码类型.md
        - 关闭selinux: system/关闭selinux.md
        - 开启图形界面: system/开启图形界面.md
        - 改变系统时区: system/改变系统时区.md
        - 磁盘容量扩充: system/磁盘容量扩充.md
        - 网卡不存在: system/网卡不存在.md
        - 通过shell命令写文件: system/通过shell命令写文件.md
    - 虚拟机迁移:
        - libguestfs架构: 虚拟机迁移/libguestfs架构.md
        - 以ova为例virt-v2v磁盘转换流程: 虚拟机迁移/以ova为例virt-v2v磁盘转换流程.md
        - virt-p2v-make-disk脚本分析: 虚拟机迁移/virt-p2v-make-disk脚本分析.md
        - virt-p2v介绍: 虚拟机迁移/virt-p2v介绍.md
        - virt-p2v磁盘转换流程: 虚拟机迁移/virt-p2v磁盘转换流程.md
    - Spice:
        - 简介: spice/简介.md
        - 使用范例: spice/使用范例.md
        - 函数所在文件: spice/函数所在文件.md
    - Python:
        - event线程: python/event线程.md
        - json格式处理: python/json格式处理.md
        - 执行shell命令: python/执行shell命令.md
        - 超时装饰器: python/超时装饰器.md
    - Other:
        - CSDN语法: other/CSDN语法.md
        - h5ai美化目录: other/h5ai美化目录.md
        - vdsm启动失败: other/vdsm启动失败.md
        - 制作iso镜像: other/制作iso镜像.md
        - 没有打印日志: other/没有打印日志.md
        - 编译安装vdsm之后主机安装失败: other/编译安装vdsm之后主机安装失败.md
    - Make:
        - 10.使用隐含规则: make/10.使用隐含规则.md
        - 11.使用make更新归档文件: make/11.使用make更新归档文件.md
        - 16.Makefile约定: make/16.Makefile约定.md
        - 4.编写规则: make/4.编写规则.md
        - 5.编写recipes: make/5.编写recipes.md
        - 6.变量: make/6.变量.md
        - 7.Makefile中的条件语句: make/7.Makefile中的条件语句.md
        - 8.转换文本函数: make/8.转换文本函数.md
        - 简介: make/简介.md
    - M4:
        - 11.文本处理的宏: m4/11.文本处理的宏.md
        - 6.条件、循环、递归: m4/6.条件、循环、递归.md
        - 简介: m4/简介.md
    - Java:
        - IO: java/IO.md
        - 作用范围级别: java/作用范围级别.md
        - synchronized关键字: java/synchronized关键字.md
    - 设计模式:
        - 设计原则: 设计模式/设计原则.md
        - 模式: 设计模式/模式.md
    - Linux网络编程:
        - 函数: linux网络编程/函数.md
        - socket通信流程: linux网络编程/socket通信流程.md
        - 简单tcp通信实现: linux网络编程/简单tcp通信实现.md
    - Gluster:
        - gluster安装: gluster/gluster安装.md
        - ovirt的gluster数据恢复bug: gluster/ovirt的gluster数据恢复bug.md
        - 清理不可用的brick: gluster/清理不可用的brick.md
        - 结点故障: gluster/结点故障.md
    - Git:
        - git rebase(修改历史提交): git/git rebase(修改历史提交).md
        - windows无法使用git克隆: git/windows无法使用git克隆.md
    - Gerrit:
        - Apache代理添加新用户: gerrit/Apache代理添加新用户.md
        - Gerrit submit change after abandoning its parent: gerrit/Gerrit submit change after abandoning its parent.md
        - 使用Apache代理路径错误: gerrit/使用Apache代理路径错误.md
        - 刷新gerrit项目列表: gerrit/刷新gerrit项目列表.md
    - Datastruct:
        - 二叉树: datastruct/二叉树.md
        - 散列表: datastruct/散列表.md
        - 红黑树: datastruct/红黑树.md
    - Command:
        - linux挂载windows共享文件夹: command/linux挂载windows共享文件夹.md
        - sed: command/sed.md
        - ssh免密登录: command/ssh免密登录.md
        - tar命令打包去掉路径前缀: command/tar命令打包去掉路径前缀.md
        - wget用法: command/wget用法.md
        - 显示文件夹大小: command/显示文件夹大小.md
        - 更新、禁用yum仓库、只下载rpm: command/更新、禁用yum仓库、只下载rpm.md
        - 添加公钥: command/添加公钥.md
    - C and c++:
        - 动态编译: c and c++/动态编译.md
        - 程序运行时间: c and c++/程序运行时间.md
    - Bash:
        - 3.基本shell功能: bash/3.基本shell功能.md
        - 4.shell内置命令: bash/4.shell内置命令.md
    - Automake:
        - 10.其它GNU工具: automake/10.其它GNU工具.md
        - 12.安装: automake/12.安装.md
        - 13.清理: automake/13.清理.md
        - 14.发布: automake/14.发布.md
        - 15.测试套件的支持: automake/15.测试套件的支持.md
        - 18.规则杂项: automake/18.规则杂项.md
        - 19.Include: automake/19.Include.md
        - 20.条件语句: automake/20.条件语句.md
        - 23.Automake不能满足使用时: automake/23.Automake不能满足使用时.md
        - 5.创建Makefile.in: automake/5.创建Makefile.in.md
        - 6.扫描configure.ac，使用aclocal: automake/6.扫描configure.ac，使用aclocal.md
        - 7.文件夹: automake/7.文件夹.md
        - 8.构建程序和库: automake/8.构建程序和库.md
        - 9.其它派生对象: automake/9.其它派生对象.md
        - 简介: automake/简介.md
    - Autogen:
        - 简介: autogen/简介.md
    - Autoconf:
        - 10.编写Autoconf宏: autoconf/10.编写Autoconf宏.md
        - 11.便携式shell编程: autoconf/11.便携式shell编程.md
        - 14.手动配置: autoconf/14.手动配置.md
        - 15.Site配置: autoconf/15.Site配置.md
        - 4.初始化和输出文件: autoconf/4.初始化和输出文件.md
        - 5.现有测试: autoconf/5.现有测试.md
        - 6.编写测试: autoconf/6.编写测试.md
        - 7.测试结果: autoconf/7.测试结果.md
        - 8.使用M4编程: autoconf/8.使用M4编程.md
        - 9.使用M4sh编程: autoconf/9.使用M4sh编程.md
        - 简介: autoconf/简介.md
    - Algorithm:
        - 复杂度分析: algorithm/复杂度分析.md
        - 选择排序: algorithm/选择排序.md
theme: readthedocs